import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./reactQueryProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Factory Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <Toaster position="bottom-center" />
        <ReactQueryProvider>
          <main>{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
